name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Ler a versão do Node.js do arquivo .nvmrc
      - name: Read Node.js version from .nvmrc
        id: node-version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      # Passo 3: Configurar o Node.js usando a versão especificada no .nvmrc
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Passo 4: Instalar dependências
      - name: Install dependencies
        run: yarn install

      # Passo 5: Rodar os testes
      - name: Run tests
        run: yarn test
